"""
NOTIFICATION SERVICE
====================
Central service for creating and managing notifications.

Two categories of notifications exist in this system:

  SYSTEM notifications (sent_by_id=NULL, target_type='system')
  ─────────────────────────────────────────────────────────────
  Auto-generated by business logic:
    • Low attendance alert (< 75%)
    • Semester promotion confirmation
    • Graduation confirmation
    • HOD attendance edit alert (to teacher who marked it)
    • Welcome notification on account creation

  MANUAL notifications (sent_by_id=HOD_user_id, target_type='manual')
  ─────────────────────────────────────────────────────────────────────
  HOD explicitly composes and sends:
    • To a single student
    • To a single teacher
    • To ALL students in a semester (broadcast)
    • To ALL teachers in the department (broadcast)
    • To ALL students in the entire department (broadcast)

RULES:
  1. Only HOD can send manual notifications
  2. HOD can only target users in their own department
  3. Title must be at least 3 characters
  4. Message must be at least 10 characters
  5. Broadcasts create one row per recipient — no single "broadcast" row
     This means each person can independently mark their copy as read
"""

from datetime import datetime
from app import db
from app.models.notification import Notification
from app.models.teacher      import Teacher
from app.models.student      import Student
from app.models.user         import User


# ══════════════════════════════════════════════════════════════════════
#  VALIDATION
# ══════════════════════════════════════════════════════════════════════

MIN_TITLE_LEN   = 3
MIN_MESSAGE_LEN = 10
VALID_TYPES     = ('info', 'warning', 'success', 'danger')


def _validate_content(title, message, notif_type):
    title   = (title   or '').strip()
    message = (message or '').strip()

    if len(title) < MIN_TITLE_LEN:
        return None, None, None, (
            f'Title must be at least {MIN_TITLE_LEN} characters.'
        )
    if len(message) < MIN_MESSAGE_LEN:
        return None, None, None, (
            f'Message must be at least {MIN_MESSAGE_LEN} characters.'
        )
    if notif_type not in VALID_TYPES:
        return None, None, None, (
            f'Invalid type. Allowed: {", ".join(VALID_TYPES)}.'
        )
    return title, message, notif_type, None


def _get_hod_teacher(hod_user):
    return Teacher.query.filter_by(user_id=hod_user.id, is_hod=True).first()


# ══════════════════════════════════════════════════════════════════════
#  SINGLE-TARGET SEND
# ══════════════════════════════════════════════════════════════════════

def send_to_user(sender_user, recipient_user_id,
                 title, message, notif_type='info'):
    """
    HOD sends a notification to ONE specific user (student or teacher).

    Validates:
      - Sender must be an HOD
      - Recipient must exist and be in HOD's department
      - Content length requirements

    Returns: (notification, None) | (None, error_msg)
    """
    hod = _get_hod_teacher(sender_user)
    if not hod:
        return None, 'Only an HOD can send notifications.'

    title, message, notif_type, err = _validate_content(
        title, message, notif_type
    )
    if err:
        return None, err

    recipient = User.query.get(recipient_user_id)
    if not recipient or not recipient.is_active:
        return None, 'Recipient not found or account is inactive.'

    # Verify recipient is in HOD's department
    dept_id = hod.department_id
    in_dept = False

    if recipient.is_teacher:
        t = Teacher.query.filter_by(user_id=recipient.id).first()
        in_dept = t and t.department_id == dept_id
    elif recipient.is_student:
        s = Student.query.filter_by(user_id=recipient.id,
                                    is_graduated=False).first()
        in_dept = s and s.department_id == dept_id
    else:
        return None, 'Can only send to teachers or students in your department.'

    if not in_dept:
        return None, 'Recipient does not belong to your department.'

    notif = Notification(
        user_id     = recipient_user_id,
        sent_by_id  = sender_user.id,
        target_type = 'manual',
        type        = notif_type,
        title       = title,
        message     = message,
    )
    db.session.add(notif)
    db.session.commit()
    return notif, None


# ══════════════════════════════════════════════════════════════════════
#  BROADCAST SENDS
# ══════════════════════════════════════════════════════════════════════

def send_to_semester(hod_user, semester, program_type,
                     title, message, notif_type='info'):
    """
    HOD broadcasts a notification to ALL active students
    in a specific semester + program_type within their department.

    Each student gets their OWN copy (independent read state).

    Returns: (sent_count, None) | (0, error_msg)
    """
    hod = _get_hod_teacher(hod_user)
    if not hod:
        return 0, 'Only an HOD can send notifications.'

    title, message, notif_type, err = _validate_content(
        title, message, notif_type
    )
    if err:
        return 0, err

    students = (
        Student.query
        .filter_by(
            department_id = hod.department_id,
            semester      = semester,
            program_type  = program_type,
            is_graduated  = False,
        )
        .join(Student.user)
        .filter(User.is_active == True)
        .all()
    )

    if not students:
        return 0, (
            f'No active {program_type} students found '
            f'in Semester {semester}.'
        )

    now = datetime.utcnow()
    for student in students:
        db.session.add(Notification(
            user_id     = student.user_id,
            sent_by_id  = hod_user.id,
            target_type = 'manual',
            type        = notif_type,
            title       = title,
            message     = message,
            created_at  = now,
        ))

    db.session.commit()
    return len(students), None


def send_to_all_students(hod_user, title, message, notif_type='info'):
    """
    HOD broadcasts to ALL active students in their department
    (across all semesters and program types).

    Returns: (sent_count, None) | (0, error_msg)
    """
    hod = _get_hod_teacher(hod_user)
    if not hod:
        return 0, 'Only an HOD can send notifications.'

    title, message, notif_type, err = _validate_content(
        title, message, notif_type
    )
    if err:
        return 0, err

    students = (
        Student.query
        .filter_by(department_id=hod.department_id, is_graduated=False)
        .join(Student.user)
        .filter(User.is_active == True)
        .all()
    )

    if not students:
        return 0, 'No active students found in your department.'

    now = datetime.utcnow()
    for student in students:
        db.session.add(Notification(
            user_id     = student.user_id,
            sent_by_id  = hod_user.id,
            target_type = 'manual',
            type        = notif_type,
            title       = title,
            message     = message,
            created_at  = now,
        ))

    db.session.commit()
    return len(students), None


def send_to_all_teachers(hod_user, title, message, notif_type='info'):
    """
    HOD broadcasts to ALL active teachers (non-HOD) in their department.

    Returns: (sent_count, None) | (0, error_msg)
    """
    hod = _get_hod_teacher(hod_user)
    if not hod:
        return 0, 'Only an HOD can send notifications.'

    title, message, notif_type, err = _validate_content(
        title, message, notif_type
    )
    if err:
        return 0, err

    teachers = (
        Teacher.query
        .filter_by(
            department_id = hod.department_id,
            is_hod        = False,
            is_active     = True,
        )
        .all()
    )

    if not teachers:
        return 0, 'No active teachers found in your department.'

    now = datetime.utcnow()
    for teacher in teachers:
        db.session.add(Notification(
            user_id     = teacher.user_id,
            sent_by_id  = hod_user.id,
            target_type = 'manual',
            type        = notif_type,
            title       = title,
            message     = message,
            created_at  = now,
        ))

    db.session.commit()
    return len(teachers), None


def send_to_teacher(hod_user, teacher_user_id,
                    title, message, notif_type='info'):
    """
    HOD sends to ONE specific teacher in their department.
    Convenience wrapper around send_to_user() with a teacher-specific
    department check.

    Returns: (notification, None) | (None, error_msg)
    """
    return send_to_user(
        hod_user, teacher_user_id, title, message, notif_type
    )


# ══════════════════════════════════════════════════════════════════════
#  HOD SENT-NOTIFICATIONS HISTORY
# ══════════════════════════════════════════════════════════════════════

def get_sent_notifications(hod_user, limit=100):
    """
    Fetch all notifications sent BY this HOD (manual ones only).
    Used on the HOD's "Sent" page — shows what was broadcast and to whom.

    Returns list of dicts: {notification, recipient_name, is_read}
    """
    hod = _get_hod_teacher(hod_user)
    if not hod:
        return []

    sent = (
        Notification.query
        .filter_by(sent_by_id=hod_user.id, target_type='manual')
        .order_by(Notification.created_at.desc())
        .limit(limit)
        .all()
    )
    return sent


def get_sent_summary(hod_user):
    """
    Stats for the HOD notification dashboard:
      total_sent, read_count, unread_count
    """
    hod = _get_hod_teacher(hod_user)
    if not hod:
        return {}

    total  = Notification.query.filter_by(
        sent_by_id=hod_user.id, target_type='manual').count()
    read   = Notification.query.filter_by(
        sent_by_id=hod_user.id, target_type='manual', is_read=True).count()

    return {
        'total_sent'  : total,
        'read_count'  : read,
        'unread_count': total - read,
    }


# ══════════════════════════════════════════════════════════════════════
#  GENERIC INBOX (for teachers and HODs)
#  Students use student_service.get_notifications()
# ══════════════════════════════════════════════════════════════════════

def get_inbox(user, unread_only=False, limit=50):
    """
    Fetch notifications for any user (teacher, HOD, principal).
    Returns list of Notification objects, newest first.
    """
    q = user.notifications
    if unread_only:
        q = q.filter_by(is_read=False)
    return q.limit(limit).all()


def get_inbox_unread_count(user):
    """Quick count of unread notifications for navbar badge."""
    try:
        return user.notifications.filter_by(is_read=False).count()
    except Exception:
        return 0


def mark_read(user, notification_id):
    """Mark a single notification as read. Verifies ownership."""
    notif = Notification.query.get(notification_id)
    if not notif or notif.user_id != user.id:
        return False, 'Notification not found.'
    if notif.is_read:
        return True, None
    notif.mark_as_read()
    db.session.commit()
    return True, None


def mark_all_read(user):
    """Mark all unread notifications as read. Returns count marked."""
    unread = user.notifications.filter_by(is_read=False).all()
    now    = datetime.utcnow()
    for n in unread:
        n.is_read = True
        n.read_at = now
    if unread:
        db.session.commit()
    return len(unread)
