"""Add is_qr_scan column to Attendance

Revision ID: 152cf5500026
Revises: f51bc6ebf6a7
Create Date: 2026-04-26 09:55:15.134121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152cf5500026'
down_revision = 'f51bc6ebf6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('program_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=5), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('is_hod', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('admission_year', sa.String(length=9), nullable=False),
    sa.Column('program_type', sa.String(length=5), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_graduated', sa.Boolean(), nullable=False),
    sa.Column('graduation_semester', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.String(length=9), nullable=True),
    sa.Column('graduation_reason', sa.Text(), nullable=True),
    sa.Column('graduated_at', sa.DateTime(), nullable=True),
    sa.Column('graduated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['graduated_by_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('marked_by_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_reason', sa.Text(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('original_status', sa.String(length=10), nullable=True),
    sa.Column('is_qr_scan', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['marked_by_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'date', name='uq_student_subject_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('qr_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('expiry_minutes', sa.Integer(), nullable=False))
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_qr_sessions_token'), ['token'], unique=True)
        batch_op.drop_column('expires_at')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_qr_sessions_token'))
        batch_op.alter_column('token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('expiry_minutes')
        batch_op.drop_column('attendance_date')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_subject_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))

    op.drop_table('attendance')
    op.drop_table('teacher_subjects')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('subjects')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
